version: "3.8"

services:
  baemin-server:
    image: ${DOCKER_HUB_USERNAME}/baemin-server:latest
    container_name: baemin-server
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always