version: "3.8"

services:
  baemin-server:
    image: ${DOCKER_HUB_USERNAME}/baemin-server:latest
    container_name: baemin-server
    ports:
      - "8080:8080"
    environment:
      - DOCKER_HUB_USERNAME=${DOCKER_HUB_USERNAME}
      - ACCESS_TOKEN_VALID_TIME=${ACCESS_TOKEN_VALID_TIME}
      - REFRESH_TOKEN_VALID_TIME=${REFRESH_TOKEN_VALID_TIME}
      - JWT_SECRET=${JWT_SECRET}
    restart: always