version: "3.8"

services:
  baemin-server:
    image: clapp123/baemin-server:latest
    container_name: baemin-server
    ports:
      - "8080:8080"
    environment:
      - DOCKER_HUB_USERNAME=clapp123
      - ACCESS_TOKEN_VALID_TIME=10800000
      - REFRESH_TOKEN_VALID_TIME=86400000
      - JWT_SECRET=59405d43e5c98e1f0e49f87455d3269b22292f3a6162a05d8f6d6f5108f91845
    restart: always
