name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: 빌드 후 도커 허브에 푸쉬
    runs-on: ubuntu-latest

    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: JDK 버전 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: application-prod.yml 환경변수 주입
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application-prod.yml

        env:
          spring.datasource.url: ${{secrets.MYSQL_URL}}
          spring.datasource.username: ${{secrets.MYSQL_USERNAME}}
          spring.datasource.password: ${{secrets.MYSQL_PASSWORD}}
          jwt.secret: ${{secrets.JWT_SECRET}}

      - name: JAR 빌드
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test -i --no-daemon -Dspring.profiles.active=prod

      - name: 도커 허브 로그인
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}

      - name: 도커 이미지 빌드
        run: docker build -t ${{secrets.DOCKER_HUB_USERNAME}}/baemin-server:latest .

      - name: 도커 이미지 푸쉬
        run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/baemin-server:latest

      - name: AWS에 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_IP}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PASSWORD}}
          port: ${{secrets.EC2_PORT}}
          script: |
            cd /home/ubuntu/baemin

            echo "DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}" > .env

            sudo docker-compose down
            sudo docker-compose pull
            sudo docker-compose up -d
            sudo docker image prune -f
